/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Heartbeat
         * @description This route is used to check the server is up and running.
         */
        get: operations["heartbeat_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db-heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Db Heartbeat
         * @description This route is used to check the connection to the database is working.
         */
        get: operations["db_heartbeat_db_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versions
         * @description This route returns the version of the current running API.
         */
        get: operations["versions_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login user and set JWT cookies.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh the access token using the refresh token.
         */
        post: operations["refresh_token_auth_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout user by clearing the auth cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get the currently logged in user.
         */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Update the current user's name.
         */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/me/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description Send a password reset email to the current user.
         */
        post: operations["request_password_reset_me_request_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Layers
         * @description List layers.
         */
        get: operations["list_layers_layers_get"];
        put?: never;
        /**
         * Create Layer
         * @description Create layer.
         */
        post: operations["create_layer_layers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layer
         * @description Get a layer by id.
         */
        get: operations["get_layer_layers__layer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Node
         * @description Create node.
         */
        post: operations["create_node_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Nodes
         * @description Query nodes with optional filters. At least one of layer_id, parent_node_id, or ids required.
         *
         *     All provided filters are combined with AND. Results are ordered by name.
         *     Replaces GET /nodes — use this for layer listing, parent picking, and selection detail.
         */
        post: operations["query_nodes_nodes_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node
         * @description Get node by id, including computed data and full ancestor chain.
         */
        get: operations["get_node_nodes__node_id__get"];
        /**
         * Update Node
         * @description Update node.
         */
        put: operations["update_node_nodes__node_id__put"];
        post?: never;
        /**
         * Delete Node
         * @description Delete a node (order>=1 only). Cascades to child nodes via FK.
         */
        delete: operations["delete_node_nodes__node_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk Update Node
         * @description Bulk update nodes (name/color only — does not change parent assignment).
         */
        put: operations["bulk_update_node_nodes_bulk_put"];
        post?: never;
        /**
         * Bulk Delete Nodes
         * @description Bulk delete nodes, orphaning or reparenting their children first.
         *
         *     child_action='orphan'   → children lose their parent assignment.
         *     child_action='reparent' → children are moved to reparent_node_id (same layer).
         *     Only valid for order>=1 layers.
         */
        delete: operations["bulk_delete_nodes_nodes_bulk_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/bulk/reparent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk Reparent Nodes
         * @description Bulk reparent nodes to a new parent (or orphan them).
         *
         *     All nodes must be in the same layer. parent_node_id must be in the layer
         *     directly above, or null to remove the parent assignment.
         */
        put: operations["bulk_reparent_nodes_nodes_bulk_reparent_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Nodes
         * @description Merge multiple nodes into a new node in the same layer.
         *
         *     Creates a new node with the given name/parent, reparents all children
         *     to the new node, and deletes the originals. Only valid for order>=1 layers.
         */
        post: operations["merge_nodes_nodes_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Zip Assignments
         * @description List zip assignments for an order=0 layer, optionally filtered by parent territory.
         */
        get: operations["list_zip_assignments_zip_assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Zip Assignments
         * @description Query zip codes, joining against zip_assignments for the given layer.
         */
        post: operations["query_zip_assignments_zip_assignments_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/{layer_id}/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Bulk Assign Zips
         * @description Bulk assign or unassign zip codes to a territory.
         *
         *     Primary operation after lasso selection. Passing parent_node_id=null
         *     unassigns all provided zip codes (preserves rows and colors).
         */
        put: operations["bulk_assign_zips_zip_assignments__layer_id__bulk_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/{layer_id}/{zip_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zip Assignment
         * @description Get the assignment state of a specific zip code. Returns 404 if the zip is implicitly unassigned.
         */
        get: operations["get_zip_assignment_zip_assignments__layer_id___zip_code__get"];
        /**
         * Assign Zip
         * @description Assign a zip code to a territory, or update an existing assignment.
         *
         *     Passing parent_node_id=null unassigns the zip (preserves the row and color).
         */
        put: operations["assign_zip_zip_assignments__layer_id___zip_code__put"];
        post?: never;
        /**
         * Reset Zip
         * @description Reset a zip code to its default state (removes the assignment row).
         *
         *     The zip remains implicitly present on the map but reverts to white with no territory.
         */
        delete: operations["reset_zip_zip_assignments__layer_id___zip_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zip-assignments/{layer_id}/{zip_code}/geography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zip With Geography Default
         * @description Get a zip's assignment state, falling back to geography defaults if no row exists.
         */
        get: operations["get_zip_with_geography_default_zip_assignments__layer_id___zip_code__geography_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Map
         * @description Search nodes and zip codes within a map by name / zip code prefix.
         */
        get: operations["search_map_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/{layer_id}/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tile
         * @description Get a vector tile for a specific layer at the given tile coordinates.
         *
         *     For order=0 (zip) layers: queries geography_zip_codes LEFT JOIN zip_assignments.
         *     For order>=1 layers: queries pre-computed node geometries.
         *     Data fields from data_field_config are included as flat numeric properties.
         */
        get: operations["get_tile_tiles__layer_id___z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/warm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Warm Cache */
        get: operations["warm_cache_tiles_warm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Maps
         * @description List maps for the current user, each with its active job and import state.
         */
        get: operations["list_maps_maps_get"];
        put?: never;
        /**
         * Create Map
         * @description Create a map from a previously uploaded and parsed document.
         */
        post: operations["create_map_maps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Map
         * @description Get a single map with its active job and import state.
         */
        get: operations["get_map_maps__map_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spatial/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Features In Lasso
         * @description Select all features from a layer that intersect with a lasso polygon.
         *
         *     For order=0 (zip) layers: returns zip_codes (strings) from geography_zip_codes.
         *     For order>=1 layers: returns node IDs (integers) from nodes.
         */
        post: operations["select_features_in_lasso_spatial_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}/export/ztt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Ztt
         * @description Export a map's zip-to-territory hierarchy as an Excel (.xlsx) file.
         *
         *     Columns: zip_code | <layer order=1 name> | <layer order=2 name> | …
         *     One row per assigned zip code, with the full ancestor chain filled in.
         */
        get: operations["export_ztt_maps__map_id__export_ztt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Spreadsheet
         * @description Accept an Excel/.ztt file, stream it to S3, and enqueue background parsing.
         *
         *     Returns immediately with document_id. The client should poll
         *     GET /maps/uploads/{document_id} until status is 'ready' or 'failed'.
         */
        post: operations["upload_spreadsheet_maps_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/uploads/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload Status
         * @description Poll the parse status of an uploaded file.
         */
        get: operations["get_upload_status_maps_uploads__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssignZip
         * @description Assign or update a single zip code's territory assignment.
         *
         *     PUT with parent_node_id=null unassigns the zip (nulls the FK, preserves the row and color).
         *     DELETE /layers/{layer_id}/zips/{zip_code} resets the zip (removes the row entirely).
         */
        AssignZip: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Color */
            color?: string | null;
        };
        /** Body_upload_spreadsheet_maps_uploads_post */
        Body_upload_spreadsheet_maps_uploads_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Tab Index
             * @default 0
             */
            tab_index: number;
        };
        /**
         * BulkAssignZips
         * @description Bulk assign or unassign a list of zip codes to a territory.
         *
         *     Primary operation after lasso selection: select zips on map, assign to territory.
         *     parent_node_id=null unassigns all provided zip codes (preserves rows and colors).
         */
        BulkAssignZips: {
            /** Zip Codes */
            zip_codes: string[];
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Color */
            color?: string | null;
        };
        /**
         * BulkDeleteNodes
         * @description Bulk delete nodes, with a declared strategy for their children.
         *
         *     All node_ids must belong to the same layer (order >= 1).
         *     child_action='orphan'   → children's parent_node_id set to null.
         *     child_action='reparent' → children moved to reparent_node_id (same layer, not in delete set).
         */
        BulkDeleteNodes: {
            /** Node Ids */
            node_ids: number[];
            /**
             * Child Action
             * @enum {string}
             */
            child_action: "orphan" | "reparent";
            /** Reparent Node Id */
            reparent_node_id?: number | null;
        };
        /**
         * BulkUpdateNode
         * @description BulkUpdateNode.
         */
        BulkUpdateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Id */
            id: number;
        };
        /**
         * CreateLayer
         * @description CreateLayer.
         */
        CreateLayer: {
            /** Name */
            name: string;
            /** Map Id */
            map_id: string;
        };
        /**
         * CreateMap
         * @description DTO for POST /maps.
         *
         *     References a previously uploaded and parsed document. The raw spreadsheet
         *     data stays in S3 and is read by the background import worker.
         */
        CreateMap: {
            /** Document Id */
            document_id: string;
            /** Name */
            name: string;
            /** Layers */
            layers: components["schemas"]["LayerSetup"][];
            /** Data Fields */
            data_fields: components["schemas"]["DataFieldSetup"][];
        };
        /**
         * CreateNode
         * @description CreateNode.
         */
        CreateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Layer Id */
            layer_id: number;
        };
        /**
         * DataFieldConfig
         * @description Data field config entry stored on a map.
         */
        DataFieldConfig: {
            /** Field */
            field: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number";
            /** Aggregations */
            aggregations: ("sum" | "avg")[];
        };
        /**
         * DataFieldSetup
         * @description DataFieldSetup.
         */
        DataFieldSetup: {
            /** Name */
            name: string;
            /** Header */
            header: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number";
            /**
             * Aggregations
             * @default []
             */
            aggregations: ("sum" | "avg")[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeartbeatResponseDTO
         * @description Heartbeat response DTO.
         */
        HeartbeatResponseDTO: {
            /**
             * Timenow
             * Format: date-time
             */
            timenow: string;
        };
        /**
         * Layer
         * @description Layer.
         */
        Layer: {
            /** Id */
            id: number;
            /** Map Id */
            map_id: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
        };
        /**
         * LayerSetup
         * @description LayerSetup.
         */
        LayerSetup: {
            /** Name */
            name: string;
            /** Header */
            header: string;
        };
        /**
         * LoginDTO
         * @description POST model for logging in a user.
         */
        LoginDTO: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /**
         * Map
         * @description Map.
         */
        Map: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Tile Version
             * @default 0
             */
            tile_version: number;
            /** Data Field Config */
            data_field_config?: components["schemas"]["DataFieldConfig"][] | null;
            active_job?: components["schemas"]["MapJob"] | null;
            import_state: components["schemas"]["MapImportState"];
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * MapImportState
         * @description Import lifecycle state embedded in Map responses.
         *
         *     Covers the import phase (after POST /maps). The parse phase lives on MapUploadStatus.
         *     Non-nullable on Map — all maps in this system are created via the upload flow.
         */
        MapImportState: {
            /**
             * Status
             * @enum {string}
             */
            status: "importing" | "complete" | "failed";
            /** Step */
            step?: string | null;
            /** Warnings */
            warnings?: string[] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * MapJob
         * @description Background recompute job for a map (geometry or data). Import lifecycle is tracked separately via MapImportState.
         */
        MapJob: {
            /** Id */
            id: string;
            /**
             * Job Type
             * @enum {string}
             */
            job_type: "recompute_geometry" | "recompute_data";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "complete" | "failed";
            /** Step */
            step?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * MapUploadFailed
         * @description Returned by GET /maps/uploads/{id} when parsing failed.
         */
        MapUploadFailed: {
            /** Document Id */
            document_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
            /** Error */
            error: string;
            /** Error Reason */
            error_reason?: string | null;
        };
        /**
         * MapUploadParsing
         * @description Returned by both POST /maps/uploads and GET /maps/uploads/{id} while parsing.
         */
        MapUploadParsing: {
            /** Document Id */
            document_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "parsing";
        };
        /**
         * MapUploadReady
         * @description Returned by GET /maps/uploads/{id} once parsing is complete.
         *
         *     The frontend uses headers + suggested_layers to render the wizard configuration
         *     step, and preview_rows to show the user a sample of their data.
         */
        MapUploadReady: {
            /** Document Id */
            document_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
            /** Headers */
            headers: string[];
            /** Suggested Layers */
            suggested_layers: string[];
            /** Preview Rows */
            preview_rows: (string | number | null)[][];
            /** Row Count */
            row_count: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * MergeNodes
         * @description Merge multiple nodes into a single new node.
         *
         *     All node_ids must belong to the same layer (order >= 1).
         *     Children (child nodes or zip assignments) are reparented to the new node.
         *     parent_node_id must be in the layer directly above, or null.
         */
        MergeNodes: {
            /** Node Ids */
            node_ids: number[];
            /** Name */
            name: string;
            /** Parent Node Id */
            parent_node_id: number | null;
        };
        /**
         * Node
         * @description Node.
         */
        Node: {
            /** Id */
            id: number;
            /** Layer Id */
            layer_id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Parent Node Id */
            parent_node_id?: number | null;
            /**
             * Child Count
             * @default 0
             */
            child_count: number;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Ancestors */
            ancestors?: components["schemas"]["NodeAncestor"][] | null;
        };
        /**
         * NodeAncestor
         * @description One ancestor level in a node's hierarchy chain.
         */
        NodeAncestor: {
            /** Layer Id */
            layer_id: number;
            /** Layer Name */
            layer_name: string;
            /** Node Id */
            node_id: number;
            /** Node Name */
            node_name: string;
            /** Node Color */
            node_color: string;
        };
        /**
         * NodeQuery
         * @description Body for POST /nodes/query.
         *
         *     At least one of layer_id, parent_node_id, or ids must be provided.
         *     All conditions are combined with AND.
         */
        NodeQuery: {
            /** Layer Id */
            layer_id?: number | null;
            /** Parent Node Id */
            parent_node_id?: number | null;
            /** Ids */
            ids?: number[] | null;
            /** Search */
            search?: string | null;
        };
        /**
         * PaginatedNodes
         * @description Paginated nodes response.
         */
        PaginatedNodes: {
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaginatedZipAssignments
         * @description Paginated zip assignments response.
         */
        PaginatedZipAssignments: {
            /** Zip Assignments */
            zip_assignments: components["schemas"]["ZipAssignment"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * RegisterDTO
         * @description POST model for creating a new user.
         */
        RegisterDTO: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ReparentNodes
         * @description Bulk reparent nodes to a new parent (or no parent).
         *
         *     All node_ids must belong to the same layer.
         *     parent_node_id must be in the layer directly above, or null to orphan.
         */
        ReparentNodes: {
            /** Node Ids */
            node_ids: number[];
            /** Parent Node Id */
            parent_node_id: number | null;
        };
        /**
         * SearchResultItem
         * @description A single search result — either a territory node or a zip code.
         */
        SearchResultItem: {
            /**
             * Type
             * @enum {string}
             */
            type: "node" | "zip";
            /** Id */
            id: number | string;
            /** Name */
            name: string;
            /** Layer Id */
            layer_id: number;
            /** Layer Name */
            layer_name: string;
            /** Color */
            color: string;
            /** Centroid */
            centroid?: number[] | null;
        };
        /**
         * SearchResults
         * @description Search results grouped from nodes and zip codes across a map.
         */
        SearchResults: {
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
            /** Total */
            total: number;
        };
        /** SpatialSelectRequest */
        SpatialSelectRequest: {
            /** Layer Id */
            layer_id: number;
            polygon: components["schemas"]["Polygon"];
        };
        /** SpatialSelectResponse */
        SpatialSelectResponse: {
            /** Count */
            count: number;
            /** Nodes */
            nodes: number[];
            /**
             * Zip Codes
             * @default []
             */
            zip_codes: string[];
        };
        /**
         * UpdateMeDTO
         * @description PATCH body for updating the current user's profile.
         */
        UpdateMeDTO: {
            /** Name */
            name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /**
         * UpdateNode
         * @description UpdateNode.
         */
        UpdateNode: {
            /** Parent Node Id */
            parent_node_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /**
         * User
         * @description User schema.
         */
        User: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponseDTO
         * @description Version response DTO.
         */
        VersionResponseDTO: {
            /** Api */
            api: string | null;
        };
        /**
         * ZipAssignment
         * @description A zip code's assignment state on a map layer.
         *
         *     Represents a zip_assignments row. Implicit zips (no row) are only visible
         *     via MVT tiles and are not returned by the API as individual objects.
         */
        ZipAssignment: {
            /** Zip Code */
            zip_code: string;
            /** Layer Id */
            layer_id: number;
            /** Parent Node Id */
            parent_node_id?: number | null;
            /** Color */
            color: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ZipQuery
         * @description Body for POST /zip-assignments/query.
         *
         *     layer_id is always required. zip_codes narrows to a specific set (e.g. lasso selection).
         *     search filters by zip code prefix/substring.
         */
        ZipQuery: {
            /** Layer Id */
            layer_id: number;
            /** Zip Codes */
            zip_codes?: string[] | null;
            /** Search */
            search?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    heartbeat_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponseDTO"];
                };
            };
        };
    };
    db_heartbeat_db_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    versions_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponseDTO"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_reset_me_request_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_layers_layers_get: {
        parameters: {
            query: {
                map_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_layer_layers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLayer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_layers__layer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_node_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_nodes_nodes_query_post: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNodes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_node_nodes__node_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_nodes__node_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_node_nodes_bulk_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateNode"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_nodes_nodes_bulk_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteNodes"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_reparent_nodes_nodes_bulk_reparent_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReparentNodes"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_nodes_nodes_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeNodes"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zip_assignments_zip_assignments_get: {
        parameters: {
            query: {
                layer_id: number;
                parent_node_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZipAssignments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_zip_assignments_zip_assignments_query_post: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZipQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZipAssignments"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_assign_zips_zip_assignments__layer_id__bulk_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAssignZips"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zip_assignment_zip_assignments__layer_id___zip_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_zip_zip_assignments__layer_id___zip_code__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignZip"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_zip_zip_assignments__layer_id___zip_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zip_with_geography_default_zip_assignments__layer_id___zip_code__geography_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                zip_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZipAssignment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_map_search_get: {
        parameters: {
            query: {
                map_id: string;
                q: string;
                layer_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_tiles__layer_id___z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    warm_cache_tiles_warm_get: {
        parameters: {
            query: {
                map_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_maps_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Map"][];
                };
            };
        };
    };
    create_map_maps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMap"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Map"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_maps__map_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Map"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_features_in_lasso_spatial_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpatialSelectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialSelectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_ztt_maps__map_id__export_ztt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_spreadsheet_maps_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_spreadsheet_maps_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapUploadParsing"] | components["schemas"]["MapUploadReady"] | components["schemas"]["MapUploadFailed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_status_maps_uploads__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapUploadParsing"] | components["schemas"]["MapUploadReady"] | components["schemas"]["MapUploadFailed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
