"""enable postgis.

Revision ID: faabb954ac33
Revises: ade4809321e2
Create Date: 2025-11-22 14:06:34.674275-08:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]


# revision identifiers, used by Alembic.
revision: str = "faabb954ac33"
down_revision: str | None = "ade4809321e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: ade4809321e2 to faabb954ac33."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION citext;")
    op.execute("CREATE EXTENSION postgis;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: faabb954ac33 to ade4809321e2."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION postgis;")
    op.execute("DROP EXTENSION citext;")
    # ### end Alembic commands ###
