"""init models.

Revision ID: 700f9e50e2e7
Revises: faabb954ac33
Create Date: 2026-01-14 19:50:59.580648-08:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "700f9e50e2e7"
down_revision: str | None = "faabb954ac33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: faabb954ac33 to 700f9e50e2e7."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "data_field_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maps")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "layers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_layers_map_id_maps")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layers")),
        sa.UniqueConstraint("name", "map_id", name=op.f("uq_layers_name")),
        sa.UniqueConstraint("order", "map_id", name=op.f("uq_layers_order")),
    )
    op.create_table(
        "user_map_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "MEMBER", native_enum=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_user_map_roles_map_id_maps")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_map_roles_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_map_roles")),
        sa.UniqueConstraint("user_id", "role", "map_id", name=op.f("uq_user_map_roles_user_id")),
    )
    op.create_index(
        "uq_map_owner", "user_map_roles", ["map_id"], unique=True, postgresql_where=sa.text("role = 'OWNER'")
    )
    op.create_geospatial_table(
        "nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_cache_key", sa.String(), nullable=False),
        sa.Column("data_inputs_cache_key", sa.String(), nullable=False),
        sa.Column(
            "geom",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z3",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z7",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z11",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z15",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("geom_cache_key", sa.String(), nullable=False),
        sa.Column("geom_inputs_cache_key", sa.String(), nullable=False),
        sa.Column("parent_node_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], name=op.f("fk_nodes_layer_id_layers")),
        sa.ForeignKeyConstraint(["parent_node_id"], ["nodes.id"], name=op.f("fk_nodes_parent_node_id_nodes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        sa.UniqueConstraint("layer_id", "name", name=op.f("uq_nodes_layer_id")),
    )
    op.create_geospatial_index(
        "idx_nodes_geom", "nodes", ["geom"], unique=False, postgresql_using="gist", postgresql_ops={}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: 700f9e50e2e7 to faabb954ac33."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index("idx_nodes_geom", table_name="nodes", postgresql_using="gist", column_name="geom")
    op.drop_geospatial_table("nodes")
    op.drop_index("uq_map_owner", table_name="user_map_roles", postgresql_where=sa.text("role = 'OWNER'"))
    op.drop_table("user_map_roles")
    op.drop_table("layers")
    op.drop_table("users")
    op.drop_table("maps")
    # ### end Alembic commands ###
