"""added initial models.

Revision ID: dc2613846b7f
Revises: faabb954ac33
Create Date: 2026-04-18 22:34:07.362536-07:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc2613846b7f"
down_revision: str | None = "faabb954ac33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: faabb954ac33 to dc2613846b7f."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "geography_zip_codes",
        sa.Column("zip_code", sa.String(length=5), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column(
            "geom",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z3",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z3_merc",
            Geometry(srid=3857, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z7",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z7_merc",
            Geometry(srid=3857, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z11",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z11_merc",
            Geometry(srid=3857, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("zip_code", name=op.f("pk_geography_zip_codes")),
    )
    op.create_geospatial_index(
        "idx_geography_zip_codes_geom",
        "geography_zip_codes",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_geography_zip_codes_geom_z11",
        "geography_zip_codes",
        ["geom_z11"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_geography_zip_codes_geom_z3",
        "geography_zip_codes",
        ["geom_z3"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_geography_zip_codes_geom_z7",
        "geography_zip_codes",
        ["geom_z7"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "map_uploads",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("tab_index", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("parsing", "ready", "importing", "complete", "failed", native_enum=False), nullable=False
        ),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("suggested_layers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("preview_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("layer_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("import_step", sa.String(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_uploads")),
    )
    op.create_index("idx_map_uploads_s3_key", "map_uploads", ["s3_key"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "maps",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tile_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("data_field_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("source_upload_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_upload_id"], ["map_uploads.id"], name=op.f("fk_maps_source_upload_id_map_uploads")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maps")),
    )
    op.create_table(
        "user_upload_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role", sa.Enum("OWNER", native_enum=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"], ["map_uploads.id"], name=op.f("fk_user_upload_roles_upload_id_map_uploads")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_upload_roles_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_upload_roles")),
        sa.UniqueConstraint("user_id", "upload_id", name=op.f("uq_user_upload_roles_user_id")),
    )
    op.create_index("idx_user_upload_roles_user_id", "user_upload_roles", ["user_id"], unique=False)
    op.create_table(
        "layers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("map_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_layers_map_id_maps")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layers")),
        sa.UniqueConstraint("name", "map_id", name=op.f("uq_layers_name")),
        sa.UniqueConstraint("order", "map_id", name=op.f("uq_layers_order")),
    )
    op.create_index("idx_layers_map_id", "layers", ["map_id"], unique=False)
    op.create_table(
        "map_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("map_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("job_type", sa.Enum("recompute_geometry", "recompute_data", native_enum=False), nullable=False),
        sa.Column("status", sa.Enum("pending", "processing", "complete", "failed", native_enum=False), nullable=False),
        sa.Column("step", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_map_jobs_map_id_maps")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_jobs")),
    )
    op.create_index("idx_map_jobs_map_id", "map_jobs", ["map_id"], unique=False)
    op.create_table(
        "user_map_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "MEMBER", native_enum=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_user_map_roles_map_id_maps")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_map_roles_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_map_roles")),
        sa.UniqueConstraint("user_id", "role", "map_id", name=op.f("uq_user_map_roles_user_id")),
    )
    op.create_index(
        "uq_map_owner", "user_map_roles", ["map_id"], unique=True, postgresql_where=sa.text("role = 'OWNER'")
    )
    op.create_table(
        "mvt_tile_cache",
        sa.Column("layer_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=10), nullable=False),
        sa.Column("z", sa.SmallInteger(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("tile_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], name=op.f("fk_mvt_tile_cache_layer_id_layers")),
        sa.PrimaryKeyConstraint("layer_id", "endpoint", "z", "x", "y", name=op.f("pk_mvt_tile_cache")),
    )
    op.execute(
        sa.text(
            "ALTER TABLE mvt_tile_cache SET ("
            "autovacuum_vacuum_scale_factor = 0.01, "
            "autovacuum_analyze_scale_factor = 0.01"
            ")"
        )
    )
    op.create_geospatial_table(
        "nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "geom_z3",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z3_merc",
            Geometry(srid=3857, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z7",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z7_merc",
            Geometry(srid=3857, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z11",
            Geometry(srid=4326, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geom_z11_merc",
            Geometry(srid=3857, dimension=2, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("parent_node_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], name=op.f("fk_nodes_layer_id_layers")),
        sa.ForeignKeyConstraint(["parent_node_id"], ["nodes.id"], name=op.f("fk_nodes_parent_node_id_nodes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        sa.UniqueConstraint("layer_id", "name", name=op.f("uq_nodes_layer_id")),
    )
    op.create_geospatial_index(
        "idx_nodes_geom_z11", "nodes", ["geom_z11"], unique=False, postgresql_using="gist", postgresql_ops={}
    )
    op.create_geospatial_index(
        "idx_nodes_geom_z3", "nodes", ["geom_z3"], unique=False, postgresql_using="gist", postgresql_ops={}
    )
    op.create_geospatial_index(
        "idx_nodes_geom_z7", "nodes", ["geom_z7"], unique=False, postgresql_using="gist", postgresql_ops={}
    )
    op.create_index("idx_nodes_layer_id", "nodes", ["layer_id"], unique=False)
    op.create_index("idx_nodes_parent_node_id", "nodes", ["parent_node_id"], unique=False)
    op.create_table(
        "zip_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("layer_id", sa.Integer(), nullable=False),
        sa.Column("zip_code", sa.String(length=5), nullable=False),
        sa.Column("parent_node_id", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], name=op.f("fk_zip_assignments_layer_id_layers")),
        sa.ForeignKeyConstraint(["parent_node_id"], ["nodes.id"], name=op.f("fk_zip_assignments_parent_node_id_nodes")),
        sa.ForeignKeyConstraint(
            ["zip_code"], ["geography_zip_codes.zip_code"], name=op.f("fk_zip_assignments_zip_code_geography_zip_codes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zip_assignments")),
        sa.UniqueConstraint("layer_id", "zip_code", name=op.f("uq_zip_assignments_layer_id")),
    )
    op.create_index("idx_zip_assignments_parent_node_id", "zip_assignments", ["parent_node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: dc2613846b7f to faabb954ac33."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_zip_assignments_parent_node_id", table_name="zip_assignments")
    op.drop_table("zip_assignments")
    op.drop_index("idx_nodes_parent_node_id", table_name="nodes")
    op.drop_index("idx_nodes_layer_id", table_name="nodes")
    op.drop_geospatial_index("idx_nodes_geom_z7", table_name="nodes", postgresql_using="gist", column_name="geom_z7")
    op.drop_geospatial_index("idx_nodes_geom_z3", table_name="nodes", postgresql_using="gist", column_name="geom_z3")
    op.drop_geospatial_index("idx_nodes_geom_z11", table_name="nodes", postgresql_using="gist", column_name="geom_z11")
    op.drop_geospatial_table("nodes")
    op.drop_table("mvt_tile_cache")
    op.drop_index("uq_map_owner", table_name="user_map_roles", postgresql_where=sa.text("role = 'OWNER'"))
    op.drop_table("user_map_roles")
    op.drop_index("idx_map_jobs_map_id", table_name="map_jobs")
    op.drop_table("map_jobs")
    op.drop_index("idx_layers_map_id", table_name="layers")
    op.drop_table("layers")
    op.drop_index("idx_user_upload_roles_user_id", table_name="user_upload_roles")
    op.drop_table("user_upload_roles")
    op.drop_table("maps")
    op.drop_table("users")
    op.drop_index("idx_map_uploads_s3_key", table_name="map_uploads")
    op.drop_table("map_uploads")
    op.drop_geospatial_index(
        "idx_geography_zip_codes_geom_z7",
        table_name="geography_zip_codes",
        postgresql_using="gist",
        column_name="geom_z7",
    )
    op.drop_geospatial_index(
        "idx_geography_zip_codes_geom_z3",
        table_name="geography_zip_codes",
        postgresql_using="gist",
        column_name="geom_z3",
    )
    op.drop_geospatial_index(
        "idx_geography_zip_codes_geom_z11",
        table_name="geography_zip_codes",
        postgresql_using="gist",
        column_name="geom_z11",
    )
    op.drop_geospatial_index(
        "idx_geography_zip_codes_geom", table_name="geography_zip_codes", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("geography_zip_codes")
    # ### end Alembic commands ###
