"""map ppt export models.

Revision ID: 5d2284c12aed
Revises: bd9a96a540db
Create Date: 2026-04-28 19:31:10.015502-07:00

"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, cast

from alembic import op as _op

if TYPE_CHECKING:
    from geoalchemy2.alembic_helpers import GeoAlchemyOperations

    op: GeoAlchemyOperations = cast("GeoAlchemyOperations", _op)
else:
    op = _op  # type: ignore[assignment]
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5d2284c12aed"
down_revision: str | None = "bd9a96a540db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade revisions: bd9a96a540db to 5d2284c12aed."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_exports",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("map_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "in_progress", "generating", "complete", "failed", native_enum=False),
            nullable=False,
        ),
        sa.Column("total_slides", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], name=op.f("fk_map_exports_map_id_maps")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_exports")),
    )
    op.create_index("idx_map_exports_map_id", "map_exports", ["map_id"], unique=False)
    op.create_table(
        "map_export_slides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("export_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("layer_id", sa.Integer(), nullable=False),
        sa.Column("parent_node_id", sa.Integer(), nullable=True),
        sa.Column("bbox_min_lng", sa.Float(), nullable=True),
        sa.Column("bbox_min_lat", sa.Float(), nullable=True),
        sa.Column("bbox_max_lng", sa.Float(), nullable=True),
        sa.Column("bbox_max_lat", sa.Float(), nullable=True),
        sa.Column("node_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_s3_key", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["export_id"], ["map_exports.id"], name=op.f("fk_map_export_slides_export_id_map_exports")
        ),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], name=op.f("fk_map_export_slides_layer_id_layers")),
        sa.ForeignKeyConstraint(
            ["parent_node_id"], ["nodes.id"], name=op.f("fk_map_export_slides_parent_node_id_nodes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_export_slides")),
        sa.UniqueConstraint("export_id", "order", name=op.f("uq_map_export_slides_export_id")),
    )
    op.create_index("idx_map_export_slides_export_id", "map_export_slides", ["export_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade revisions: 5d2284c12aed to bd9a96a540db."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_map_export_slides_export_id", table_name="map_export_slides")
    op.drop_table("map_export_slides")
    op.drop_index("idx_map_exports_map_id", table_name="map_exports")
    op.drop_table("map_exports")
    # ### end Alembic commands ###
