name: terramaps
services:
  api:
    image: terramaps/api:latest
    build:
      context: ..
      dockerfile: api/Dockerfile
      target: api
    env_file:
      - .env.docker-compose
      - .env.local
    command: --reload
    ports:
      - "8042:8000"
    volumes:
      - ./src:/app/src
      - type: bind
        source: ./openapi.json
        target: /app/openapi.json
    healthcheck:
      test: ["CMD", "/app/.venv/bin/httpx", "http://localhost:8000/heartbeat"]
      interval: 10s
      timeout: 10s
      retries: 6
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
  worker:
    image: terramaps/worker-local:latest
    build:
      context: ..
      dockerfile: api/Dockerfile
      target: worker-local
    env_file:
      - .env.docker-compose
      - .env.local
    volumes:
      - ./src:/app/src
    command:
      - "auto-restart"
      - "--directory"
      - "/app/src/"
      - "--recursive"
      - "--pattern"
      - "*.py"
      - "--"
      - "/app/.venv/bin/celery"
      - "--app"
      - "src.workers:celery_app"
      - "worker"
      - "--queues"
      - "terramaps"
      - "--loglevel"
      - "info"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "/app/.venv/bin/celery inspect ping -d celery@$$HOSTNAME"]
      interval: 30s
      retries: 6
      timeout: 10s
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
  flower:
    image: mher/flower
    command: ["celery", "flower"]
    ports:
      - "5558:5555"
    environment:
      FLOWER_PORT: 5555
      FLOWER_BASIC_AUTH: "admin:admin"
      CELERY_BROKER_URL: amqp://rabbitmq:5672
    depends_on:
      worker:
        condition: service_healthy
  db:
    image: terramaps/postgres:latest
    build:
      dockerfile: Dockerfile.postgres
    hostname: postgres
    environment:
      POSTGRES_USER: terramaps
      POSTGRES_PASSWORD: terramaps
      POSTGRES_DB: app
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "terramaps"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
  migrations:
    image: terramaps/migrations-local:latest
    build:
      context: ..
      dockerfile: api/Dockerfile
      target: migrations-local
    env_file:
      - .env.docker-compose
      - .env.local
    volumes:
      - ./src:/app/src
      - ./src/migrations/versions:/app/src/migrations/versions
    # deploy:
    # resources:
    #   limits:
    #     cpus: "0.5"
    #     memory: 512M
    depends_on:
      db:
        condition: service_healthy
  minio:
    image: bitnamilegacy/minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: terramaps:public
      MINIO_BROWSER: on
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
volumes:
  minio_data:
