name: Deploy
on: [workflow_call]
permissions:
  id-token: write
  contents: read
jobs:
  redeploy-dev:
    name: Force new deployment of services in dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with IAM
        uses: terramaps/terramaps-infra/.github/actions/iam-auth@main
        with:
          role-arn: arn:aws:iam::336519019521:role/github/deploy_role
      - name: Redeploy dev environment
        run: |
          aws ecs update-service --cluster terramaps-dev-cluster --service api --force-new-deployment
          aws ecs update-service --cluster terramaps-dev-cluster --service worker --force-new-deployment
          aws ecs update-service --cluster terramaps-dev-cluster --service app --force-new-deployment
